set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g history-limit 10000
set -g mouse on
unbind-key -q -n MouseDrag1Pane
unbind-key -q -n MouseDragEnd1Pane
unbind-key -q -T copy-mode MouseDrag1Pane
unbind-key -q -T copy-mode MouseDragEnd1Pane
unbind-key -q -T copy-mode MouseDown1Pane
unbind-key -q -T copy-mode-vi MouseDrag1Pane
unbind-key -q -T copy-mode-vi MouseDragEnd1Pane
unbind-key -q -T copy-mode-vi MouseDown1Pane
set -g status off
