github.com:
    users:
        tysongoulding:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: tysongoulding
